apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: facuxfdz-app-tls
  namespace: facuxfdz
spec:
  dnsNames:
    - facuxfdz.com
  secretName: facuxfdz-app-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer